/*TABLA TEMPORAL*/
CREATE TABLE temporal(
    NOMBRE_EMPLEADO VARCHAR(100),
    APELLIDO_EMPLEADO VARCHAR(100),
    DIRECCION_EMPLEADO VARCHAR(100),
    TELEFONO_EMPLEADO VARCHAR(100),
    GENERO_EMPLEADO VARCHAR(100),
    FECHA_NACIMIENTO_EMPLEADO VARCHAR(100),
    TITULO_DEL_EMPLEADO VARCHAR(100),
    NOMBRE_PACIENTE VARCHAR(100),
    APELLIDO_PACIENTE VARCHAR(100),
    DIRECCION_PACIENTE VARCHAR(100),
    TELEFONO_PACIENTE VARCHAR(100),
    GENERO_PACIENTE VARCHAR(100),
    FECHA_NACIMIENTO_PACIENTE VARCHAR(100),
    ALTURA VARCHAR(100),
    PESO VARCHAR(100),
    FECHA_EVALUACION VARCHAR(100),
    SINTOMA_DEL_PACIENTE VARCHAR(100),
    DIAGNOSTICO_DEL_SINTOMA VARCHAR(100),
    RANGO_DEL_DIAGNOSTICO VARCHAR(100),
    FECHA_TRATAMIENTO VARCHAR(100),
    TRATAMIENTO_APLICADO VARCHAR(100)
);
DROP TABLE temporal;

/*TABLA TITULO*/
CREATE TABLE titulo (
    id_titulo INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_titulo)
);

/*TABLA EMPLEADO*/
CREATE TABLE empleado (
    id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono INTEGER,
    fecha_nacimiento DATE NOT NULL,
    genero CHAR(1) NOT NULL,
    fk_id_titulo INT NOT NULL,
    PRIMARY KEY (id_empleado),
    FOREIGN KEY (fk_id_titulo) REFERENCES titulo(id_titulo)
);

/*TABLA TRATAMIENTO*/
CREATE TABLE tratamiento (
    id_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_tratamiento)
);

/*TABLA PACIENTE*/
CREATE TABLE paciente (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono INTEGER ,
    fecha_nacimiento DATE NOT NULL,
    genero CHAR(1) NOT NULL,
    altura NUMBER(4,2) NOT NULL,
    peso INTEGER NOT NULL,
    PRIMARY KEY (id_paciente)
);

/*TABLA PACIENTE_TRATAMIENTO*/
CREATE TABLE paciente_tratamiento (
    id_paciente_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_tratamiento DATE NOT NULL,
    fk_id_paciente INTEGER NOT NULL,
    fk_id_tratamiento INTEGER NOT NULL,
    PRIMARY KEY (id_paciente_tratamiento),
    FOREIGN KEY (fk_id_paciente) REFERENCES paciente (id_paciente),
    FOREIGN KEY (fk_id_tratamiento) REFERENCES tratamiento (id_tratamiento)
);

/*TABLA EVALUACION*/
CREATE TABLE evaluacion (
    id_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_evaluacion DATE NOT NULL,
    fk_id_empleado INTEGER NOT NULL,
    fk_id_paciente INTEGER NOT NULL,
    PRIMARY KEY (id_evaluacion),
    FOREIGN KEY (fk_id_empleado) REFERENCES empleado (id_empleado),
    FOREIGN KEY (fk_id_paciente) REFERENCES paciente (id_paciente)
);

/*TABLA SINTOMA*/
CREATE TABLE sintoma (
    id_sintoma INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_sintoma)
);

/*TABLA EVALUACION_SINTOMA*/
CREATE TABLE evaluacion_sintoma(
    id_evaluacion_sintoma INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_id_evaluacion INTEGER NOT NULL,
    fk_id_sintoma INTEGER NOT NULL,
    PRIMARY KEY (id_evaluacion_sintoma),
    FOREIGN KEY (fk_id_evaluacion) REFERENCES evaluacion (id_evaluacion),
    FOREIGN KEY (fk_id_sintoma) REFERENCES sintoma (id_sintoma)
);

/*TABLA DIAGNOSTICO*/
CREATE TABLE diagnostico(
    id_diagnostico INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_diagnostico)
);

/*TABLA DIAGNOSTICO_SINTOMA*/
CREATE TABLE diagnostico_sintoma (
    id_diagnostico_sintoma INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nivel_certeza INTEGER NOT NULL,
    fk_id_diagnostico INTEGER NOT NULL,
    fk_id_sintoma INTEGER NOT NULL,
    PRIMARY KEY (id_diagnostico_sintoma),
    FOREIGN KEY (fk_id_diagnostico) REFERENCES diagnostico (id_diagnostico),
    FOREIGN KEY (fk_id_sintoma) REFERENCES sintoma (id_sintoma)
);

/*Borrar las tablas*/
DROP TABLE titulo;
DROP TABLE empleado;
DROP TABLE tratamiento;
DROP TABLE paciente;
DROP TABLE paciente_tratamiento;
DROP TABLE evaluacion;
DROP TABLE sintoma;
DROP TABLE evaluacion_sintoma;
DROP TABLE diagnostico;
DROP TABLE diagnostico_sintoma;
