/*TABLA TEMPORAL*/
CREATE TABLE temporal(
    NOMBRE_EMPLEADO VARCHAR(100),
    APELLIDO_EMPLEADO VARCHAR(100),
    DIRECCION_EMPLEADO VARCHAR(100),
    TELEFONO_EMPLEADO VARCHAR(100),
    GENERO_EMPLEADO VARCHAR(100),
    FECHA_NACIMIENTO_EMPLEADO VARCHAR(100),
    TITULO_DEL_EMPLEADO VARCHAR(100),
    NOMBRE_PACIENTE VARCHAR(100),
    APELLIDO_PACIENTE VARCHAR(100),
    DIRECCION_PACIENTE VARCHAR(100),
    TELEFONO_PACIENTE VARCHAR(100),
    GENERO_PACIENTE VARCHAR(100),
    FECHA_NACIMIENTO_PACIENTE VARCHAR(100),
    ALTURA VARCHAR(100),
    PESO VARCHAR(100),
    FECHA_EVALUACION VARCHAR(100),
    SINTOMA_DEL_PACIENTE VARCHAR(100),
    DIAGNOSTICO_DEL_SINTOMA VARCHAR(100),
    RANGO_DEL_DIAGNOSTICO VARCHAR(100),
    FECHA_TRATAMIENTO VARCHAR(100),
    TRATAMIENTO_APLICADO VARCHAR(100)
);
DROP TABLE temporal;

SELECT * FROM temporal;
TRUNCATE TABLE temporal;

